# Generated by Django 5.0.3 on 2025-04-19 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=25)),
                ('level', models.IntegerField(default=1)),
                ('race', models.CharField(max_length=25)),
                ('alignment', models.CharField(max_length=25)),
                ('experience', models.IntegerField(default=0)),
                ('ability_scores', models.JSONField(default=dict)),
                ('saving_throws', models.JSONField(default=dict)),
                ('combat_stats', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=dict)),
                ('equipment', models.JSONField(default=dict)),
                ('spells', models.JSONField(default=dict)),
                ('features_and_traits', models.JSONField(default=dict)),
                ('backstory', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='campaigns_joined', to=settings.AUTH_USER_MODEL)),
                ('characters', models.ManyToManyField(related_name='campaigns', to='core.character')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_campaigns', to='core.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='notes',
            field=models.ManyToManyField(related_name='campaign_notes', to='core.notes'),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('npcs', models.JSONField(default=dict)),
                ('encounters', models.JSONField(default=dict)),
                ('loot', models.JSONField(default=dict)),
                ('notes', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='scenario',
            field=models.ManyToManyField(related_name='campaigns', to='core.scenario'),
        ),
    ]
